version: '3.7'

services:
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    ports:
      - "5050:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@example.com
      - PGADMIN_DEFAULT_PASSWORD=admin123
    depends_on:
      - database
    restart: unless-stopped

  database:
    build: ./postgresql
    ports:
      - '5432'
    environment:
      - POSTGRES_USER=postgresql
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=app
    restart: unless-stopped

  backend:
    build: ./server
    depends_on:
      - database
    environment:
      - TZ=Asia/Ho_Chi_Minh
    restart: unless-stopped

  frontend:
    build: ./client
    depends_on:
      - backend
    restart: unless-stopped

  nginx:
      build: ./nginx
      ports:
        - '1503:80'
      depends_on:
        - frontend
        - backend
        - database
      restart: unless-stopped

  ollama:
    build: ./ollama
    ports:
      - '11434:11434'
    volumes:
      - ollama_models:/root/.ollama
    restart: unless-stopped

volumes:
  ollama_models:
