version: '3.7'

services:
  database:
    build: ./postgresql
    ports:
      - '5432'
    environment:
      - POSTGRES_USER=postgresql
      - POSTGRES_HOST=localhost
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=app
    restart: unless-stopped
  backend:
      build: ./server
      # ports:
      #   - '8888:8888'
      depends_on:
        - database
      restart: unless-stopped
  frontend:
      build: ./client
      # ports:
      #   - '3000:4173'
      depends_on:
        - backend
      # environment:
      #   - GOOGLE_CLIENT_ID=hard
      restart: unless-stopped
  nginx:
      build: ./nginx
      ports:
        - '1503:80'
      depends_on:
        - frontend
        - backend
        - database
      restart: unless-stopped

  ollama:
    build: ./ollama
    ports:
      - '11434:11434'
    volumes:
      - ollama_models:/root/.ollama
    restart: unless-stopped

volumes:
  ollama_models: